### ISSUE TITLE
Signature data not found.

### ISSUE THREAD

**Issue by valeriofigueira** [nextcloud/registration#101]
Apparently something is missing here, im really sorry not good at this at all.

Thank you

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- registration
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [registration] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

**Comment by yaffeweb** [comment]
I got the same error in OC 10 but Nextcloud 12 doesn't give the error. Ironically, the registration app functions properly in OC but doesn't send admin notifications in NC.

**Comment by CryptoSiD** [comment]
I think it's because the app haven't been signed using this method: https://doc.owncloud.org/server/9.0/developer_manual/app/code_signing.html

**Comment by nickvergessen** [comment]
Well be fixed for new releases.
