### ISSUE TITLE
Default private status for email field

### ISSUE THREAD

**Issue by tomastd** [nextcloud/registration#106]
Hi.
All auto-registered users have their email scope set to "contacts". 
Is it possible to set it to "private" as default? 
In public websites it should be "private" because of law, I think.
Thank you.

**Comment by pellaeon** [comment]
I guess the scope feature was introduced just recently so I'm not aware of this feature. I agree private should be a better default, will look into that, thanks!

**Comment by ChrisGCode** [comment]
I think it should be solved in the server.
See: https://github.com/nextcloud/server/issues/6582

**Comment by tomastd** [comment]
Thank you!!!

**Comment by nickvergessen** [comment]
Yeah nothing for this app. It should be the same for all users.
