### ISSUE TITLE
Remove registration attempts from the database after a while

### ISSUE THREAD

**Issue by cdamken** [nextcloud/registration#109]
I saw that after the users create their account the information is kept  in oc_regristaration.

Why aren't the old user removed?

**Comment by cdamken** [comment]
@pellaeon Can you provide any feedback?

**Comment by nickvergessen** [comment]
This is not the case anymore. I guess any remaining entries are from registration attempts that never got completed.

Should be a good idea to add a background job that cleans them up after some time.

**Comment by cdamken** [comment]
I know, I asked 3 years ago, I see you overtake the repository, I was happy with that app
