### ISSUE TITLE
Registration app in ownCloud Marketplace

### ISSUE THREAD

**Issue by cdamken** [nextcloud/registration#118]
Hi @pellaeon 

Is it possible if you upload your app in the ownCloud Marketplace?

It's really good and I heard from many persons that they used that would like to have it there to easily download it.

Best regards,
Carlos

**Comment by pellaeon** [comment]
OK, I'll do it when I release the next version.

**Comment by cdamken** [comment]
Awesome!!! Thank you a lot!

**Comment by cdamken** [comment]
@pellaeon I see there is a new version, will it be that available in ownCloud Marketplace?

**Comment by cdamken** [comment]
> OK, I'll do it when I release the next version.

@pellaeon Any news?

**Comment by nickvergessen** [comment]
Due to the more and more diverging code between ownCloud and Nextcloud not only in the backend but also in the UI, this is now not a goal anymore, so I'm closing this.
