### ISSUE TITLE
Toggle for not showing allowed domains if restricted

### ISSUE THREAD

**Issue by amcu** [nextcloud/registration#119]
### Steps to reproduce
1. user tries to register with emailadress, but get the information that his domain is not allowed, whilst every allowed domain is presented by name.

### Expected behaviour
either disable listing of domains to end user or allow toggling the domain listing in config page.

### Actual behaviour
every allowed domain will be presentet to user, telling that his domain is not allowed to register.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
12
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
apt
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by RonaldAlubalu** [comment]
Same here. Would be very nice to turn the list off. As for a workarround can we change the "forward" ourselfs?

**Comment by ma7cbesten** [comment]
Same here. Due to privacy and security i'd like to tell the user that his domain is not on the list of allowed domains. Thats enough for me. Just toggle a checkbox :-) Would be great to have that feature enabled.

**Comment by TSG-TSG** [comment]
I would like this feature too. In the short term, I edited

nextcloud/apps/registration/templates/domains.php

by commenting out the lines that generate the domain list:

//      foreach ($_['domains'] as $domain ){
//              echo "<p class='hint'>";
//              p($domain);
//              echo "</p>";
//      }

One could also edit the verbiage in that file:

        <li class='error'><?php p($l->t('Registration is only allowed for the following domains:')); ?>

however doing so will break the multi-language support... unless you happen to know a billion languages. :) For me, my audience is all English-speaking, so editing that wording and breaking localization isn't an issue. :)

**Comment by BoehmFloh** [comment]
> I would like this feature too. In the short term, I edited
> 
> nextcloud/apps/registration/templates/domains.php
> 
> by commenting out the lines that generate the domain list

The methode you mentioned above by out-commenting the loop for displaying the domains on the page worked for me until today.
I just played around a bit with curl so I can check (semi-automated) if my manual changes to the domains.php file are still active after an update of nextcloud or the registration app.
So I sent the following request:
`curl https://<domain/ip>/ocs/v1.php/registration/v1/validate\?format\=json -H "OCS-APIRequest:true" -v --data "username=foobar&displayname=foobar&email=foobar@example.com"`

The site returns all domains which are allowed to register.

@pellaeon Is there a way to simply comment out some part (server-side) so the server doesn't returns all domains?
