### ISSUE TITLE
Stretched logo when registering an E-Mail

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/registration#122]
### Steps to reproduce
1. Install registration app on Nextcloud 13
2. Add a custom logo to Nextcloud (Take one that is large and has another aspect ratio than the original NC logo)
3. Register a new E-Mail
4. Look at an ugly stretched logo

### Expected behaviour
The logo should only appear once.

### Actual behaviour
The logo is twice on the "registration" page. One is the normal one and one is a stretched version of it.
In Google Chrome the image is more strechted than in Firefox, but there is a always a second version of the logo that is stretched when looking at the HTML code.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** apache2

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from NC 12

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows / Ubuntu

**Comment by nickvergessen** [comment]
Can not reproduce with latest Nextcloud
