### ISSUE TITLE
Show privacy policy and log user consent for GDPR compliance

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/registration#140]
To be compliant with EU GDPR, registration should have an option to show the privacy policy of the nextcloud instance to the user and prompt for consent.
Actual "Theming" had this implemented some days ago (without the consent).

Without this, registration is legally not usable in many cases within the EU or with EU based users if you do not get user consent another way.

The **active** user consent (no pre-filled checkbox) should be logged to the database (ideally together with the version of the displayed privacy policy).

**Comment by nickvergessen** [comment]
Integration with Terms of service was brought in last year:
https://apps.nextcloud.com/apps/terms_of_service

That should be usable to cover this case
