### ISSUE TITLE
Registration not sending E-Mails

### ISSUE THREAD

**Issue by realvale** [nextcloud/registration#143]
### Expected behaviour
When user registers, mail get's sent to the user and admin.

### Actual behaviour
No mails sent. No errors found. Log says the mail was sent out.

### Server configuration
**Operating system**: Debian 9

**Web server:** Apache2

**Database:** MariaDB/MySQL

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page)13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Official Website

**Addition:** It was working fine till a few days ago. Even after reinstalling nextcloud, still not working. I didn't change anything on the mail server. I don't know what to do anymore.

**EDIT:** Every other mail is being sent correctly. Test-Mails work, Forgot Password too.

**Comment by dimm0** [comment]
Same

**Comment by dimm0** [comment]
Same

**Comment by JohanBoshoffWebAware** [comment]
Can anyone explain why only the verification link gets sent to a new user.  No Welcome email gets sent after verification and the admin also do not get notified about a new user.

This thread has been dead for a while now and I need the notifications enabled.  Please assist.

**Comment by nickvergessen** [comment]
Welcome email is dicussed in #137

The general email issue I can not reproduce. It works fine here and other wise logs something.
