### ISSUE TITLE
Set disk space for new users

### ISSUE THREAD

**Issue by hellomotow** [nextcloud/registration#145]
Shouldn't there be an option to set the disk space for the new users?

**Comment by pellaeon** [comment]
OK, so I was mistaken, this feature used to work like this in older version of nextcloud. I will add this to the road map.

**Comment by dacoex** [comment]
Isn't the quota inherited from the standard quota set in user admin?

**Comment by nickvergessen** [comment]
Nextcloud itself has a "default quota" field which can be used for this
