### ISSUE TITLE
Translate message to Swedish

### ISSUE THREAD

**Issue by rollanders** [nextcloud/registration#195]
I would like to have a swedish message instead of 
"Your account has been successfully created, but it still needs approval from an administrator."
I can fix it is I know where - Transifex? 

Or please add "Ditt konto har registrerats men måste först accepteras av en administratör."

**Comment by nickvergessen** [comment]
You can translate the app now on transifex:
https://www.transifex.com/nextcloud/nextcloud/translate/#sv/registration/294253999
