### ISSUE TITLE
Registration code instead of a link in registration-email

### ISSUE THREAD

**Issue by fds2610** [nextcloud/registration#198]
FEATURE REQUEST:
To educate users not to click on links in emails, I would like to ask for a new feature:
Do not provide a link in your registration-confirmation email but provide a one-time-code. This code shall be entered manually (or copy/paste) into the next screen shown after sending the registration email.

### Steps to reproduce
1. Click on "Register"
2. Enter your email adress
3. verify received email

### Expected behaviour
send a code instead of a link. 

**Nextcloud version:** 18.0.2

**Comment by hex-m** [comment]
Such a code could also be send via other channels (Signal, WhatsApp,..) and would basically be the "invite code" that was mentioned in #173.

**Comment by nickvergessen** [comment]
The token is now also in the email as text since #234
