### ISSUE TITLE
Registration app fails on ownCloud 10.4.0.4

### ISSUE THREAD

**Issue by lewmilburn** [nextcloud/registration#203]
### Steps to reproduce
1. Activate registration as usual.
2. Click 'register' button on login screen.
3. Enter email and click verify

### Expected behaviour
Should send verification email and allow signup.

### Actual behaviour
No email arrives and this happens:
![image](https://user-images.githubusercontent.com/63267144/78612081-654d9c00-7860-11ea-9b6a-c987be8bf6ae.png)
No logs can be found.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**OwnCloud version:** 10.4.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Comment by pellaeon** [comment]
I cannot debug without logs. This error seems to originate from the web server. Did you check Apache logs?

**Comment by nickvergessen** [comment]
Closing due to lack of feedback. Feel free to comment again with more information.
