### ISSUE TITLE
Nextcloud 19 compatibility ?

### ISSUE THREAD

**Issue by JonathanTreffler** [nextcloud/registration#210]
When will this app be compatible with Nextcloud 19 ?

**Comment by nickvergessen** [comment]
@pellaeon I created a "stable19" branch, so we don't by accident break the old version with new changes.
I guess the only thing missing is to make a release from there.

As currently only you are the maintainer of the app in the appstore and have the certificate, can you do this?

**Comment by TessyPowder** [comment]
@pellaeon Any Updates ?

**Comment by nsturtz** [comment]
Is it working

**Comment by staukini** [comment]
@pellaeon Is the stable19 brunch stable enough to update the App in the Nextcloud-appstore?

**Comment by nickvergessen** [comment]
Yes

**Comment by nsturtz** [comment]
Has it been updated?

**Comment by nsturtz** [comment]
What is the status?

**Comment by kescherCode** [comment]
> @pellaeon Has it been updated?

It has not,

**Comment by eguindos** [comment]
Any news?

Nextcloud 19 is here, but cannot update it due to this problem with registration compatibility.

**Comment by nickvergessen** [comment]
I got a new certificate, on thursday 19.0.2 will come out shipping the new master certificate to validate the signature and then I will push it to the appstore

**Comment by eguindos** [comment]
Fantastic !! 

Thanks a lot.

**Comment by nickvergessen** [comment]
0.5.0 is now in the appstore:
https://apps.nextcloud.com/apps/registration/releases?platform=19#19

**Comment by eguindos** [comment]
Thanks a lot. I see now I can upgrade Nextcloud to ver. 19

Good job. Thanks !!!
