### ISSUE TITLE
Unable to send registration link second time

### ISSUE THREAD

**Issue by subendra** [nextcloud/registration#235]
### Expected behaviour
must be able to send link multiple times or 2/3 times

### Actual behaviour
only send registration link for the first time but when we again try to register again it displays message saying the user is already in pending state. NO registration link is sent second time

### Server configuration
Cent OS

APACHE

MARIADB

PHP7

Nexcloud 17

Registration App in Nextcloud
Can anybody share me something on this?

**Comment by nickvergessen** [comment]
Nextcloud 17 is running out of support this month. Can you retry on a more recent version?

**Comment by nickvergessen** [comment]
Should work now, otherwise it will be fixed by expiring old links as per #250
