### ISSUE TITLE
Allowed email domains wildcards not working

### ISSUE THREAD

**Issue by cparker15** [nextcloud/registration#238]
The README of this repo lists the following as a feature:
* Allow-list with email domains (including wildcard) to register with

### Steps to reproduce
1. Configure allowed email domains to include a domain with a wildcard (e.g.: example.com;*. example.com)
2. Attempt to register a new user with an email address that should match the wildcard pattern (e.g.: user@foo.example.com)

### Expected behaviour
User receives a registration email

### Actual behaviour
User is directed to a page listing the allowed domains, including the wildcard domain(s) as-is

**Comment by nickvergessen** [comment]
Yeah it's a new feature coming in the Nextcloud 20 version which will release soon
