### ISSUE TITLE
'Blank' in username causing problems

### ISSUE THREAD

**Issue by C-7** [nextcloud/registration#241]
During the registration user is free to set a 'natural' username like "Tim Lee" including a  'blank'. 
Apparently those whitespace subsequently causes problems like explained in [https://github.com/nextcloud/calendar/issues/2537](https://github.com/nextcloud/calendar/issues/2537) (closed because of 'duplication')
Not sure if 2537 is a symptom or an issue.  Perhaps 'blanks' in username could be substituted by 'underscores' (don't know if other characters/internationalisation is affected) but kept in display name.

**Comment by nickvergessen** [comment]
This doesn't need fixing here. Whitespaces are supported so it needs to be fixed in the server issue: https://github.com/nextcloud/server/issues/21642
