### ISSUE TITLE
Missing token leads to admin_approval_required bypass

### ISSUE THREAD

**Issue by maralorn** [nextcloud/registration#249]
### Steps to reproduce
1. Install and enable registration 0.5.1
2. Set "admin_approval_required" to "yes" (in the UI).
3. Start a registration process, by entering an e-mail-address.
4. Click on the confirmation link or enter the verification code.
5. Enter a username and a password, submit form.

### Expected behaviour
Step 4 should result in a form with an action link that points to the correct createAccount endpoint.

Step 5 should result in a success message to the user and a create a **disabled** user account.

### Actual behaviour
Step 4 shows in the log the error `Undefined index: token at <...>/nextcloud/apps/registration/templates/form/user.php#6`.
The page that loads, looks as expected to the user, but when I inspect the html the form contains an empty action field like this: `<form action="" method="post">`. (Which looks like it is from line 6 in the template where the error occured.)

Step 5 leads to the same page being reloaded. To the user it looks like nothing happened, **but the user account got created with the given username and it is *enabled* and requires no admin approval anymore.** Also the same error appears in the log again (which is not very surprising).

### Comment

Even if the first error the "Undefined index: token" is caused by an administration error on my side. (I can‘t tell.) I think the fact that this leads to a circumvention of the admin approval is a security issue.

### Server configuration
**Operating system**: CentOs 7

**Web server:** Apache

**Database:** MySQL (10.3.22-MariaDB)

**PHP version:** PHP 7.4

**Nextcloud version:** 20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** I have updated this nextcloud from 17 to 20 in manual steps from one major version to the next, I admit it was a bit bumpy, but as far as I can tell at the end everything was fine and is working.

**Where did you install Nextcloud from:** The 20.0.0.0 tarball on the download page as of today.

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - event_update_notification: 1.1.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - polls: 1.5.4
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - registration: 0.5.1
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - user_ldap
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "overwriteprotocol": "https",
        "skeletondirectory": "",
        "default_language": "de",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "mail_smtpauth": 1
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox 81.0 (64-bit)

**Operating system:** NixOS 20.09

#### Web server error log
<details>
<summary>Web server error log</summary>

In the logs I have there is definitely nothing related to this issue.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"X4dQNU1onRvWqDOlJGfe3QAAABQ","level":3,"time":"2020-10-14T19:23:33+00:00","remoteAddr":"2001:16b8:2a27:db00:64ce:e6c9:6905:9ff7","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/registration/register/9z7iHeFBGnbX5P2z2PLQBN7PE2jZ6XYn/reMZeBYyaM","message":{"Exception":"Error","Message":"Undefined index: token at /var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php#6","Code":0,"Trace":[{"file":"/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php","line":6,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined index: token","/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php",6,{"file":"/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php","additionalParams":{"email":"test-user3@maralorn.de","email_is_login":false,"username":"","message":""},"_":{"email":"test-user3@maralorn.de","email_is_login":false,"username":"","message":"","requesttoken":"0HYKTxC/Ehny/Gmhhr5UbKPmsu7tQb02s9JUuTY0eVg=:ljdQe3WKeSGEqQ/D6f07BtGM5JqmKtwA1eBn2AJOFik="},"l":{"__class__":"OC\\L10N\\LazyL10N"},"theme":{"__class__":"OCP\\Defaults"},"value":"0HYKTxC/Ehny/Gmhhr5UbKPmsu7tQb02s9JUuTY0eVg=:ljdQe3WKeSGEqQ/D6f07BtGM5JqmKtwA1eBn2AJOFik=","var":"requesttoken","email":"test-user3@maralorn.de","email_is_login":false,"username":"","message":"","requesttoken":"0HYKTxC/Ehny/Gmhhr5UbKPmsu7tQb02s9JUuTY0eVg=:ljdQe3WKeSGEqQ/D6f07BtGM5JqmKtwA1eBn2AJOFik="}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/Template/Base.php","line":178,"args":["/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php"],"function":"include"},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->","args":["/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php",{"email":"test-user3@maralorn.de","email_is_login":false,"username":"","message":""}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/legacy/OC_Template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[{"email":"test-user3@maralorn.de","email_is_login":false,"username":"","message":""}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->","args":[{"email":"test-user3@maralorn.de","email_is_login":false,"username":"","message":""}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->","args":[]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Registration\\Controller\\RegisterController"},"showUserForm"]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Registration\\Controller\\RegisterController","showUserForm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"secret":"9z7iHeFBGnbX5P2z2PLQBN7PE2jZ6XYn","token":"reMZeBYyaM","_route":"registration.register.showUserForm"}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/registration/register/9z7iHeFBGnbX5P2z2PLQBN7PE2jZ6XYn/reMZeBYyaM"]},{"file":"/var/www/virtual/ved/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/virtual/ved/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.9"}{"reqId":"X4dQaMI4DFef4q-cPlcEwQAAAUA","level":3,"time":"2020-10-14T19:24:26+00:00","remoteAddr":"2001:16b8:2a27:db00:64ce:e6c9:6905:9ff7","user":"--","app":"PHP","method":"POST","url":"/index.php/apps/registration/register/9z7iHeFBGnbX5P2z2PLQBN7PE2jZ6XYn/reMZeBYyaM","message":{"Exception":"Error","Message":"Undefined index: token at /var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php#6","Code":0,"Trace":[{"file":"/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php","line":6,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined index: token","/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php",6,{"file":"/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php","additionalParams":{"email":"test-user3@maralorn.de","email_is_login":false,"username":"test-user3","message":"The token is invalid"},"_":{"email":"test-user3@maralorn.de","email_is_login":false,"username":"test-user3","message":"The token is invalid","requesttoken":"7QFHabXSoCuRb3Y07HEl7RD/NA2NRVQ47x9WTgFJulc=:2iokEOChx0nQBjdF3EIc2juqYkLsdgF5hyo4N1kNgxs="},"l":{"__class__":"OC\\L10N\\LazyL10N"},"theme":{"__class__":"OCP\\Defaults"},"value":"7QFHabXSoCuRb3Y07HEl7RD/NA2NRVQ47x9WTgFJulc=:2iokEOChx0nQBjdF3EIc2juqYkLsdgF5hyo4N1kNgxs=","var":"requesttoken","email":"test-user3@maralorn.de","email_is_login":false,"username":"test-user3","message":"The token is invalid","requesttoken":"7QFHabXSoCuRb3Y07HEl7RD/NA2NRVQ47x9WTgFJulc=:2iokEOChx0nQBjdF3EIc2juqYkLsdgF5hyo4N1kNgxs="}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/Template/Base.php","line":178,"args":["/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php"],"function":"include"},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->","args":["/var/www/virtual/ved/html/nextcloud/apps/registration/templates/form/user.php",{"email":"test-user3@maralorn.de","email_is_login":false,"username":"test-user3","message":"The token is invalid"}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/legacy/OC_Template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[{"email":"test-user3@maralorn.de","email_is_login":false,"username":"test-user3","message":"The token is invalid"}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->","args":[{"email":"test-user3@maralorn.de","email_is_login":false,"username":"test-user3","message":"The token is invalid"}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->","args":[]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Registration\\Controller\\RegisterController"},"submitUserForm"]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Registration\\Controller\\RegisterController","submitUserForm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"secret":"9z7iHeFBGnbX5P2z2PLQBN7PE2jZ6XYn","token":"reMZeBYyaM","_route":"registration.register.submitUserForm"}]},{"file":"/var/www/virtual/ved/html/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/registration/register/9z7iHeFBGnbX5P2z2PLQBN7PE2jZ6XYn/reMZeBYyaM"]},{"file":"/var/www/virtual/ved/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/virtual/ved/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.9"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
No relevant logs.
</details>

**Comment by nickvergessen** [comment]
> but the user account got created with the given username and it is disabled and requires no admin approval anymore

That is how the "admin approval" was designed. The accounts get created and disabled and are then enabled by the admin to approve them or deleted by the admin.

**Comment by maralorn** [comment]
Oh, wow. I am so sorry. I truly meant *enabled*. They are *enabled* that's exactly why I am opening this issue. (Gonna fix that up there.)

**Comment by nickvergessen** [comment]
Can't reproduce this. No matter if I use enter or the button to submit the form in step 5 it still works as expected and creates the account and disables it.

**Comment by nickvergessen** [comment]
Please check if https://github.com/nextcloud/registration/commit/c20fd7321a77b7134297003a0c154f826ea513ba fixes the issue on your instance

**Comment by maralorn** [comment]
Thank you for the response I will try it out soon.

**Comment by nickvergessen** [comment]
I assume it fixes the issue.
