### ISSUE TITLE
limit to groups does not work

### ISSUE THREAD

**Issue by aixzellent** [nextcloud/registration#252]
Steps to reproduce:
Install Registration Plugin
Configure Plugin with limit to groups: myguestgroup
Register a new user myguestuser1 using the registration plugin

Expected behaviour:
myguestuser1 associated to myguestgroup

Actual behaviour
myguestuser1 associated to no group

Server configuration
Operating system:
Ubuntu 18.04 LTS

Web server:
apache2, 2.4.29

Database:
mysql, 5.7.31

PHP version:
7.2.24

Nextcloud version: (see Nextcloud admin page)
19.0.4

Updated from an older Nextcloud/ownCloud or fresh install:
fresh install

**Comment by nickvergessen** [comment]
Hi @aixzellent Thanks for your report. This will be fixed in the next version by removing the restriction option.

**Comment by aixzellent** [comment]
Dear Mr. Schilling,



Does this mean that you can no longer restrict users to one or more groups? This would not be an acceptable solution in my opinion!




Best regards
Christian Roszak

 
Innovative IT Solutions www.aixzellent.com

________________________________________________________
Dipl.-Ing. Christian Roszak
Phone: +49(0)241-6052386

E-Mail: christian.roszak@aixzellent.de
Website: http://www.aixzellent.com







-----Ursprüngliche Nachricht-----
Von: Joas Schilling <notifications@github.com>
Gesendet: Freitag 13. November 2020 16:26
An: nextcloud/registration <registration@noreply.github.com>
CC: Christian Roszak (aixzellent) <christian.roszak@aixzellent.de>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/registration] limit to groups does not work (#252)


Hi @aixzellent Thanks for your report. This will be fixed in the next version by removing the restriction option.

**Comment by aixzellent** [comment]
Hi @nickvergessen, does this mean that you can no longer restrict users to one or more groups? This would not be an acceptable solution in my opinion!

**Comment by nickvergessen** [comment]
Well people that register are not part of a group as they are guests. Limiting the app to a list of groups therefor makes no sense as all people usingg the registration app are not part of any group anyway 🤷‍♂️
There is still a setting in the admin section where you can specify a default group for the newly registered users. You mixed up to settings as one doesn't do anything and the other one is in the app's own settings section.
