### ISSUE TITLE
Having a registered users default group overrides admin approval

### ISSUE THREAD

**Issue by escribana** [nextcloud/registration#253]
### Steps to reproduce
1. Activate the app **Registration**
2. Check **Require admin approval** in _Additional settings_
3. Activate an existing group in **Registered users default group**

### Expected behaviour
A self-registering user has to wait for activation of login by an administrator

### Actual behaviour
A self-registering user gets immediate access to the default group overriding the approval of the admin

### Server configuration
**Operating system**: Ubuntu 20.04 LTS

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 19.0.0

**Where did you install Nextcloud from:**  download.nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
"no errors have been found."
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - external: 3.7.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.1.0
  - guests: 1.6.1
  - impersonate: 1.7.0
  - login_notes: 0.3.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.5.1
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - polls: 1.5.7
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - registration: 0.5.1
  - richdocuments: 3.7.5
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.1
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.escriban.ch",
            "45.76.89.170",
            "collabora.escriban.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "http:\/\/45.76.89.170\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "external",
            "calendar",
            "spreed",
            "registration"
        ],
        "defaultapp": "files",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        }
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** Firefox 82.0

**Operating system:** Ubuntu 20.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>
Don't know for what to look!
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Don't know for what to look!
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Don't know for what to look!
</details>

**Comment by nickvergessen** [comment]
Doesn't work for me. 

When I complete the registration process it says:
![Bildschirmfoto von 2020-11-17 20-35-08](https://user-images.githubusercontent.com/213943/99438735-79886a00-2914-11eb-8510-933ae67bb486.png)

And when I then try to login it says:
![Bildschirmfoto von 2020-11-17 20-35-19](https://user-images.githubusercontent.com/213943/99438791-958c0b80-2914-11eb-86fd-a594ec99a690.png)

**Comment by nickvergessen** [comment]
Closing due to lack of feedback
