### ISSUE TITLE
no warning for password policy when creating account

### ISSUE THREAD

**Issue by zouma83** [nextcloud/registration#254]
### Steps to reproduce
1. sign up to next cloud 20.0.1 ok
2. validate email address with code ok
3. create an account with a password that does not match the password policy
4. account not created (normal) but there's no indication that the password is bad quality
5. is the user try again and again, he will be ban because of the login faile warning in the log

### Expected behaviour
Tell us what should happen
in a perfect world, the user should be prompted that the password he choose does not match the password policy

### Actual behaviour
Tell us what happens instead
the user tries again and again and he became ban because of the fail2ban protection and the login failed 

### Server configuration
**Operating system**:
debian 10
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.3 php-fpm
**Nextcloud version:** (see Nextcloud admin page)
20.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
almost fresh install (one update)
**Where did you install Nextcloud from:**
latest version
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.
**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
nextcloud@ncco:/var/www/nextcloud$ php occ app:list
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - apporder: 0.11.0
  - audioplayer: 2.12.0
  - breezedark: 20.0.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - circles: 0.20.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - customproperties: 1.0.1
  - dashboard: 7.0.0
  - dav: 1.16.0
  - epubreader: 1.4.5
  - extract: 1.2.5
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_antivirus: 3.0.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - group_everyone: 0.1.6
  - groupfolders: 8.1.1
  - login_notes: 0.3.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.6.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - registration: 0.5.1
  - richdocuments: 3.7.7
  - richdocumentscode: 6.4.14
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.1
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - unsplash: 1.1.7
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - video_converter: 0.1.5
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_pdf_converter: 1.5.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
nextcloud@ncco:/var/www/nextcloud$ php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "chaumiere.ddns.net",
            "chaumiere.local",
            "192.168.0.250"
        ],
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "https:\/\/chaumiere.ddns.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes local sftp
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
*
**Operating system:**
*
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Error | PHP | Error: Undefined index: token at /var/www/nextcloud/apps/registration/templates/form/user.php#6/var/www/nextcloud/apps/registration/templates/form/user.php - line 6: OC\Log\ErrorHandler::onError(8, "Undefined index: token", "/var/www/ne ... p", 6, { file: "/va ... "})/var/www/nextcloud/lib/private/Template/Base.php - line 178: include("/var/www/ne ... p")/var/www/nextcloud/lib/private/Template/Base.php - line 150: OC\Template\Base->load("/var/www/ne ... p", { email: "ro ... "})/var/www/nextcloud/lib/private/legacy/OC_Template.php - line 180: OC\Template\Base->fetchPage({ email: "ro ... "})/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php - line 210: OC_Template->fetchPage({ email: "ro ... "})/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 123: OCP\AppFramework\Http\TemplateResponse->render()/var/www/nextcloud/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Registra ... {}, "showUserForm")/var/www/nextcloud/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OCA\\Regist ... r", "showUserForm", OC\AppFramew ... {}, { action: nu ... "})/var/www/nextcloud/lib/base.php - line 1009: OC\Route\Router->match("/apps/regis ... J")/var/www/nextcloud/index.php - line 37: OC::handleRequest()
-- | -- | --

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by vince2bir** [comment]
I noticed this too.

**Comment by nickvergessen** [comment]
See #42

**Comment by zouma83** [comment]
ok thanks for the reply
so now let's choose between registration or password policy...
thank you
issue could be close
