### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by benpryde** [nextcloud/registration#261]
After I installed the Registration app, every time i tried to register a new user with an email, this message pops up:

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: <user ip>
Request ID: H6o7Ko093hYDD6yztEs4

### Steps to reproduce
1. Install a fresh nextcloud
2. Install Registration app
3. register a new user

### Expected behaviour
Every time a user register a new email, server should send a verifying mail to user's email to verify and register

### Actual behaviour
instead of expected behavior, the above "Internal Server Error" message pops up.

### Server configuration
**Operating system**: Openmediavault 5 with linux debian

**Web server:**
Openmediavault 5
**Database:**
mariadb
**PHP version:**
-
**Nextcloud version:** (see Nextcloud admin page)
5.5.17-3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Downloaded from https://www.openmediavault.org/, installed from flash drive

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
 Registration
and other default apps, freshly installed nextcloud

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)

<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
  ),
  'datadirectory' => '/data',
  'trusted_proxies' => 
  array (
    0 => 'swag',
  ),
  'overwrite.cli.url' => 'https://mydomain',
  'overwritehost' => 'drive.mydomain.fun',
  'overwriteprotocol' => 'https',
  'trusted_domains' => 
  array (
    0 => 'drive.mydomain.fun',
  ),
  'instanceid' => 'ocz5mpntq8u7',
  'passwordsalt' => 'pwsalt',
  'secret' => 'secret',
  'dbtype' => 'mysql',
  'version' => '20.0.3.2',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextclouddb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_admin',
  'dbpassword' => 'dbpassword',
  'installed' => true,
);
</details>

### Client configuration
**Browser:**
firefox
**Operating system:**
windows10
### Logs
#### Web server error log

<details>
<summary>Web server error log</summary>

```
Internal Server Error

The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

Technical details
Remote Address: <user ip>
Request ID: H6o7Ko093hYDD6yztEs4
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[index] Error: Swift_TransportException: Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to 127.0.0.1:25 (Connection refused) at <<closure>>

 0. <<closure>>
    Swift_Transport_StreamBuffer->{closure}("*** sensitive parameters replaced ***")
 1. /config/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 272
    stream_socket_client("127.0.0.1:25", 111, "Connection refused", 10, 4, null)
 2. /config/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 58
    Swift_Transport_StreamBuffer->establishSocketConnection()
 3. /config/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 143
    Swift_Transport_StreamBuffer->initialize({protocol: "",ho ... ]})
 4. /config/www/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php line 65
    Swift_Transport_AbstractSmtpTransport->start()
 5. /config/www/nextcloud/lib/private/Mail/Mailer.php line 204
    Swift_Mailer->send(Swift_Message {}, [])
 6. /config/www/nextcloud/apps/registration/lib/Service/MailService.php line 132
    OC\Mail\Mailer->send(OC\Mail\Message {})
 7. /config/www/nextcloud/apps/registration/lib/Controller/RegisterController.php line 143
    OCA\Registration\Service\MailService->sendTokenByMail(OCA\Registration\Db\Registration {id: 1})
 8. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Registration\Controller\RegisterController->submitEmailForm("benpryde@gmail.com")
 9. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Registration ... {}, "submitEmailForm")
10. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Registration ... {}, "submitEmailForm")
11. /config/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Registrati ... r", "submitEmailForm", OC\AppFramework\ ... {}, {action: null,_r ... "})
12. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/registration/")
13. /config/www/nextcloud/index.php line 37
    OC::handleRequest()

POST /apps/registration/
from 173.245.52.104 at 2020-12-19T17:57:51+00:00
```

**Comment by benpryde** [comment]
There is another error:

[cron] Error: Exception: Not installed at <<closure>>

0. /config/www/nextcloud/lib/base.php line 653
   OC::checkInstalled()
1. /config/www/nextcloud/lib/base.php line 1091
   OC::init()
2. /config/www/nextcloud/cron.php line 42
   require_once("/config/www/nextcloud/lib/base.php")

at 2020-12-19T17:45:00+00:00

**Comment by nickvergessen** [comment]
You dont have a mail server configured.
So sending the email doesn't work.

**Comment by benpryde** [comment]
i see, is there a guide somewhere on how to set this app up?
