### ISSUE TITLE
"The token is invalid" on submitting user name

### ISSUE THREAD

**Issue by davidandres-911** [nextcloud/registration#263]
Hi!
I hope that this is the right place to ask this question:
I'm running an NC 20 installation (intern.ojhs.de).
When users want to complete the registration, they receive the mail with the code, when they enter it, they can choose a username and passwort. So far, so good. But when clicking on "register" the are confronted with the error message "Invalid token" and nothing happens. But actually the registration process is complete - when they go back to the login form and enter their data, they can login successfully. Any hints about what problem might lead to that error message and how to change it?

Any help on this would be very welcome!

Thanks in advance, David
 
### Steps to reproduce
1. register on intern.ojhs.de
2. click on approval link
3. register with desired username -> error message invalid token appears

### Expected behaviour
Tell us what should happen
registration should be completet

### Actual behaviour
Tell us what happens instead
error message

### Server configuration
**Operating system**:

**Web server:**

**Database:**
mysql, 5.7.28

**PHP version:**
7.4.10

**Nextcloud version:** (see Nextcloud admin page)
20.0.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install with version 20

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.


No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Accessability
Activity
Announcement center
Brute-force settings
Collabora online
Collabora Online - Built-in Code Server
collaborative Tags
Comments
community document server
Contacts Interaction
Custom CSS
Deck
Deleted files
External storage support
Federation
File sharing
Files automated tagging
Full text search - Files
Group folders
LDAP user and group backend
Log reader
Monitoring
Nextbackup
Nextcloud announcements
Notifications
Password policy
PDF viewer
Privacy
Recommendations
Registration (0.6.0.)
Right click
Share by mail
support
Talk
Text
Theming
Update notification
Usage survey
User status
Versions
Video Player
Weather Status
Whiteboard

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
various

**Operating system:**
windows and macos

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```e registered |  


</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Mavrag** [comment]
Having the same problem. 
The user is actually added and can login if you go back to login page.
But it just tells him The token is invalid.

**Comment by skeal** [comment]
Same here in a fresh 20 install. Sadly we are moving curently to another auth mechanism and so every User gets this error now.

**Comment by davidandres-911** [comment]
Unfortunately the problem still persists - has anyone found a workaround?

**Comment by nickvergessen** [comment]
So actually this is a bug site-effecting from the activity app and should be fixed with https://github.com/nextcloud/activity/pull/541/files

can you confirm this?

**Comment by nickvergessen** [comment]
Also the bug can only be reproduced with:
1. An admin that has push notifications configured
2. A default group for new users is selected

right?

**Comment by davidandres-911** [comment]
Thanks for your reply!


> So actually this is a bug site-effecting from the activity app and should be fixed with https://github.com/nextcloud/activity/pull/541/files
>can you confirm this?

Sorry, I don't understand the first post, can you explain that more in detail?

> Also the bug can only be reproduced with:

>    An admin that has push notifications configured
 >   A default group for new users is selected

>right?

yes, it helps to either deactivate the notifications app, the activity app or change the default group.

unfortunately I realized that when deactivating the activity app, every user (and not only admins) get a notification when a new user registers. I'm pretty sure that this behaviour wasn't that way before installing it.

**Comment by nickvergessen** [comment]
Closing as per above as this is a bug in the activity app which was solved in the latest maintenance releases
