### ISSUE TITLE
Nextcloud 20 compatibility

### ISSUE THREAD

**Issue by glOOmyART** [nextcloud/registration#264]
### Steps to reproduce
1. Update to Nextcloud 20
2. Go to Settings --> Apps
3. The app is deactivated because it does not Support Nextcloud 20

### Expected behaviour
The app should support Nextcloud 20

### Actual behaviour
It only supports Nextcloud 19

### Server configuration

**Nextcloud version:** 20.0.4

**Comment by nickvergessen** [comment]
There is a version available for 20. Just reenableit in the app management.
