### ISSUE TITLE
Username Regez won't save.

### ISSUE THREAD

**Issue by PersonalDom** [nextcloud/registration#278]
### Steps to reproduce
1. Install Registration
2. Go to settings
3. Edit 'Username Policy'

### Expected behaviour
Tell us what should happen
Green 'Saved' message at top of settings.
### Actual behaviour
Tell us what happens instead
Red 'Saving...' // Nothing happens.

**Comment by nickvergessen** [comment]
Can you post your regex?

**Comment by nickvergessen** [comment]
Also is there any error in your browser console (F12)?

**Comment by nickvergessen** [comment]
Closing due to missing feedback
