### ISSUE TITLE
Translation improvement

### ISSUE THREAD

**Issue by castillo92** [nextcloud/registration#289]
Hello, I found a little issue while translating in Transifex:

### Expected behaviour
I expect a different tip between "additional user instructions" and "additional verification-email instructions"

### Actual behaviour
In one and we had to translate a string:
> Add additional user instructions (e.g. for choosing their login name). If configured the text is displayed in the account creation step of the registration process.

In the other hand we had:
> Add additional user instructions (e.g. for choosing their login name). If configured the text is embedded in the verification-email.

I suggest to search a better tip to not repeat "e.g. for choosing their login name" in the verification email tip.

EDIT: I could not find the original string, so I created this issue instead of a especific Pull Request, sorry.

@rakekniven

**Comment by nickvergessen** [comment]
Source string is at https://github.com/nextcloud/registration/blob/master/src/AdminSettings.vue#L213

**Comment by castillo92** [comment]
Created Pull Request:

https://github.com/nextcloud/registration/pull/291
