### ISSUE TITLE
Registration notification uses wrong language

### ISSUE THREAD

**Issue by Derkades** [nextcloud/registration#290]
The email that is sent to site admins when a new account is created, is sent using the language of the registering user, not the language of the administrator. At least, that's what I assume, I get emails in unknown languages sometimes.

**Comment by nickvergessen** [comment]
Right, https://github.com/nextcloud/registration/blob/master/lib/Service/MailService.php#L175 needs to get the language injected.

**Comment by nickvergessen** [comment]
Was duplicated by #493 and fixed in #496
