### ISSUE TITLE
Problem during the registration on iphone ipad

### ISSUE THREAD

**Issue by aiherve** [nextcloud/registration#297]
### Steps to reproduce
1. On Iphone, Ipad, We should automatically log in at the end of the registration of "nextcloud talk"
2. The registration process stay blocked at the "loading" page (end of the registration). We have to kill the app and load again
3. Nextcloud 20.0.8; MySQL version "5.7.33"; behind a NAT livebox; installed with snap on ubuntu

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Please add the requested log file entries otherwise we can't help you

**Comment by aiherve** [comment]
I have this error  in the log each time someone try to register.
(I have removed the personnal infos such has the names and reqld. (reqld looks like a pass phrase but I don't know what is it ...). Thanks for your help.

{"reqId":".........","level":2,"time":"2021-04-11T08:14:41+00:00","remoteAddr":"80.215.138.8","user":"--","app":"no app in context","method":"POST","url":"/index.php/login","message":"Login failed:.....(Remote IP: 80.215.138.8)","userAgent":"Rouge-queue \u00e0 front blanc (Nextcloud Talk)","version":"20.0.8.1"}

**Comment by nickvergessen** [comment]
reqId is the request ID, it helps to find all log lines of the same request that had an error.

However that request is on url `index.php/login` and we would need one for `index.php/apps/registration`, anything with that url?

Of the given log the user agent looks super weird, or are you compiling your own Nextcloud Talk client which seems to not work. Can you try with the normal Nextcloud Talk client from the appstore?

**Comment by aiherve** [comment]
No, I am using the regular Nextcloud Talk installed from the appstore on iphone X.
The serveur has been installed one week ago with snap on ubuntu 20.

Here are the other logs I found:

Warning:

{"reqId":"VCWB373BAQ3z8RTKeMmq","level":2,"time":"2021-04-14T19:43:16+00:00","remoteAddr":"86.229.57.136","user":"--","app":"core","method":"GET","url":"/index.php/csrftoken","message":"Renewing session token failed","userAgent":"iPhone (Nextcloud Talk)","version":"20.0.8.1","id":"607b0d2140283"}

Fatal:

{"reqId":"XsUt3h43ezrz5GhUYanu","level":4,"time":"2021-04-12T18:00:56+00:00","remoteAddr":"86.229.57.136","user":"herve","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/herve/","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Système en mode maintenance.","Code":0,"Trace":[{"file":"/snap/nextcloud/27089/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"checkMaintenanceMode","class":"OCA\\DAV\\Connector\\Sabre\\MaintenancePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/snap/nextcloud/27089/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/snap/nextcloud/27089/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/snap/nextcloud/27089/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/snap/nextcloud/27089/htdocs/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/snap/nextcloud/27089/htdocs/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/snap/nextcloud/27089/htdocs/remote.php","line":167,"args":["/snap/nextcloud/27089/htdocs/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/snap/nextcloud/27089/htdocs/apps/dav/lib/Connector/Sabre/MaintenancePlugin.php","Line":85,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh) mirall/3.1.3git (build 4850) (Nextcloud)","version":"20.0.8.1","id":"607b0d21402e2"}

Error:


{"reqId":"SfuOcj7813COM7vzAjRT","level":3,"time":"2021-04-11T15:46:50+00:00","remoteAddr":"86.229.57.136","user":"Celine Tranchevent","app":"index","method":"GET","url":"/index.php/login/v2/grant","message":{"Exception":"Exception","Message":"Argument 1 passed to OC\\Core\\Controller\\ClientFlowLoginV2Controller::grantPage() must be of the type string, null given, called in /snap/nextcloud/27089/htdocs/lib/private/AppFramework/Http/Dispatcher.php on line 169","Code":0,"Trace":[{"file":"/snap/nextcloud/27089/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"grantPage"]},{"file":"/snap/nextcloud/27089/htdocs/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\ClientFlowLoginV2Controller","grantPage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.ClientFlowLoginV2.grantPage"}]},{"file":"/snap/nextcloud/27089/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login/v2/grant"]},{"file":"/snap/nextcloud/27089/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/27089/htdocs/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Core\\Controller\\ClientFlowLoginV2Controller::grantPage() must be of the type string, null given, called in /snap/nextcloud/27089/htdocs/lib/private/AppFramework/Http/Dispatcher.php on line 169","Code":0,"Trace":[{"file":"/snap/nextcloud/27089/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"grantPage","class":"OC\\Core\\Controller\\ClientFlowLoginV2Controller","type":"->","args":[null]},{"file":"/snap/nextcloud/27089/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"grantPage"]},{"file":"/snap/nextcloud/27089/htdocs/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"grantPage"]},{"file":"/snap/nextcloud/27089/htdocs/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\ClientFlowLoginV2Controller","grantPage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.ClientFlowLoginV2.grantPage"}]},{"file":"/snap/nextcloud/27089/htdocs/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login/v2/grant"]},{"file":"/snap/nextcloud/27089/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/snap/nextcloud/27089/htdocs/core/Controller/ClientFlowLoginV2Controller.php","Line":153},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0","version":"20.0.8.1","id":"607b0d21408c0"}

**Comment by aiherve** [comment]
I have searched for other log in: 
/var/log/
and
/snap/nextcloud/current/var/log

but, these directories are empty

Does the other logs I sent you, are not useful ?

On the server, I had installed  "registration", via the regular Applications space to install apps (it is version 1.2.0 for "registration" and 10.0.7 for "talk"). Does-it help ? 

Do I need to ask on the github snap forum ? (or to wait for a next snap release)

**Comment by nickvergessen** [comment]
So that last error sounds like it, but I can not reproduce this and it also doesn't seem related to the registration app.

**Comment by aiherve** [comment]
Do you think that it can be linked with the snap package ? In particular with the MySQL version "5.7.33" (not the last one > MySQL 8) that is installed with snap ? In this case, I have perhaps simply to wait for a snap update ?

**Comment by nickvergessen** [comment]
20 should work fine with it.
