### ISSUE TITLE
Please add settings option to auto append text in registration field

### ISSUE THREAD

**Issue by 12aw** [nextcloud/registration#304]
Hi,
for my instance I need an settings option to autocorrect the loginname in the user.php to email format and also apped @domain.com to the login name. 
I tried to add it myself, but didn't take over. Where do I have to add the javascript so it works?
I can send you the function if need to more quickly implement it.

Thanks and regards

**Comment by nickvergessen** [comment]
There are settings to force that the email is used as login name and a setting to force domain.com as email.
Those two should do the job

**Comment by 12aw** [comment]
Thanks for the quick response, but that's not what I meant. I meant not the email he uses for verification, but the username the user sets when registering through user.php . There's a regex option but this doesn't work with all regex somehow...

**Comment by nickvergessen** [comment]
Then you messed up your regex. Mind to share it?

**Comment by 12aw** [comment]
no problem. I tried this:  /[a-z0-9+-_]+\.[@serverdomain.de]/ and it is accepted in the settings but not working for some reason.
I also tried this actually to: /[a-z0-9+-_]+@serverdomain.de/  But it still accepts big letters...

**Comment by 12aw** [comment]
Arg, thanks for the help!
