### ISSUE TITLE
Broken as hell

### ISSUE THREAD

**Issue by hobbsecky** [nextcloud/registration#305]
.

**Comment by hobbsecky** [comment]
You know...this is a damn critical part of the whole NextCloud environment and it's literally pathetic that this is not taken more seriously.

**Comment by nickvergessen** [comment]
Hi, I would like to point out that we are a community project and want
to keep this a place that is nice and positive for everyone. These kind
of comments are not welcome. Please try to be more respectful going
forward, see our Code of Conduct for the why and what:
https://nextcloud.com/code-of-conduct/

**Comment by nickvergessen** [comment]
Seeing you removed the comment and edited the initial ticket now, I guess you found the problem on your side already.
