### ISSUE TITLE
Dynamic Groupname

### ISSUE THREAD

**Issue by htrampe** [nextcloud/registration#306]
Hi! Thx for the great work. I want to make the group dynamic. So, if a new users has registered, the new user will automaticly send to a new created group. How is that possible? I need a new Group for every new registered User. This User will creates more users in this group manually. thx for some ideas!

**Comment by nickvergessen** [comment]
Since this creates a huge security thread this is nothing we will implement.
Please note that subadmins can add any existing user to their groups and then delete the user completely.
