### ISSUE TITLE
Es wird weder eine E-Mail zum Registrieren herausgeschickt, noch eine Willkommens E-Mail

### ISSUE THREAD

**Issue by TomH1511** [nextcloud/registration#332]
### Steps to reproduce
1. Server E-Mail funktioniert und Test Mail ist angekommen.
2. Es wird weder eine E-Mail zum Registrieren herausgeschickt, noch eine Willkommens E-Mail.
3. Manuell wird diese über das Benutzer Portal verschickt

### Expected behaviour
Tell us what should happen

E-Mails werden herausgeschikt.

### Actual behaviour
Tell us what happens instead

nichts :(

### Server configuration
**Operating system**:

Linux 4.15.0 x86_64

**Web server:**

**Database:**
Art: mysql

Version: 10.3.30
**PHP version:**
8.0.8
**Nextcloud version:** (see Nextcloud admin page)
21.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

nextcloud 21.0

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
chrome
**Operating system:**
Windows
#### Web server error log
<details>
<summary>Web server error log</summary>
[Leer.txt](https://github.com/nextcloud/registration/files/6907352/Leer.txt)

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Please check your Nextcloud log
