### ISSUE TITLE
Create a way to hide the Registration button

### ISSUE THREAD

**Issue by Uncrushed7017** [nextcloud/registration#341]
Is there a way to hide the registration button? I would prefer to have a "Create Account" link at the bottom of the page.

Either this, or find a way to customize the color of the button. Because for some reason, I can't find a way to make it match the other Login button.

Thank you.

**Comment by clbreshears** [comment]
Hello,

Sorry for the late response.

I would just like to change the “Registration” button itself on the home page.

If I change the background to something other than the baby blue color, the Register button still stays the same. I don’t like that it stays that color, also, I don’t like that the text is black, and doesn’t match the white text of the Login button.

I wish there was a way to make it “match” the rest of the layout.

Thank you.

**Comment by nickvergessen** [comment]
This should be fixed by now as the button follows the server theme
