### ISSUE TITLE
Translation for "error message" when registering

### ISSUE THREAD

**Issue by francoisPE** [nextcloud/registration#350]
Hello,
I face an issue with language when registering.
 
### Steps to reproduce
1. Language is french : 
config.php > default_language="fr". 
Password_policy set and force LC, UC, number and special char. 
config.php > "password_policy": {
            "authentication": "authentication",
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "expiration": "0",
            "historySize": "0",
            "installed_version": "1.11.0",
            "maximumLoginAttempts": "0",
            "minLength": "8",
            "types": "authentication"
        },

2. Register a new mail. Give verification code in panel
3. Set up login, name, phone and password.
At that stage, I try wrong password regarding password_policy : no number
Error message send back is in english not in french.

I check password_policy : translation exists.
When I try create a user in admin console, not respecting password policy : message is in french

I try  php occ config:system:set force_language --value="fr"
It seems it gives no improvement

### Server configuration
**Operating system**: UBUNTU20.04

**Web server:** Apache 2.4

**Database:** Mariadb

**PHP version:** php 7.4.3

**Nextcloud version:** 21.0.5

**Registration** "installed_version": "1.3.0",

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/registration/pull/352/files

**Comment by francoisPE** [comment]
Amazing !
Thanks a lot for that
