### ISSUE TITLE
Admin approval doesn't work on Nextcloud 22

### ISSUE THREAD

**Issue by Ephtolens** [nextcloud/registration#365]
### Steps to reproduce
1. Activate the registration App
2. Enable the admin approval
3. Try to create an acount

### Expected behaviour
I should receive an email to approve new user and he should be in a disable state on my nextcloud users interface

### Actual behaviour
User is automaticaly created and activated without admin approval

### Server configuration
**Operating system:** Ubuntu 20.04

**Web server:**

**Database:** mariadb

**Nextcloud version:** 22

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Brave

**Operating system:** Windows

**Comment by nickvergessen** [comment]
Works fine here. Anything in the log?

**Comment by johanricher** [comment]
I confirm that it also works on me (tested on NC 22 and 23). Looks more like an issue with the email server (@Ephtolens might want to give more details in relation to that?).
