### ISSUE TITLE
Please add compatibility with Nextcloud V23

### ISSUE THREAD

**Issue by leonardohlee** [nextcloud/registration#367]
Please add compatibility with Nextcloud V23

**Comment by leonardohlee** [comment]
@nickvergessen does current version can be enabled on NV23 ?

**Comment by leonardohlee** [comment]
![image](https://user-images.githubusercontent.com/16806817/144328698-b84e574a-33a4-49f4-bfe3-9889e407010c.png)

**Comment by nickvergessen** [comment]
The update will be there when I do it. I don't need issues in all my 15 apps repos for that.

**Comment by leonardohlee** [comment]
thank you!!!
