### ISSUE TITLE
Self Registration of invited users

### ISSUE THREAD

**Issue by Bryan76** [nextcloud/registration#37]
I have a group "Internal Users."  I would like any member of that group to be able to share a folder (file) with any email address.  If that email address is not already an account on the local OwnCloud server, or on a trusted federated Own Cloud Server, then OwnCloud server would then send an email to that email address saying "John Doe has offered to share a folder with you, please click this link to create an account."  The new user would be added to a separate group, say "Invited Users."  Users in that group do not have permission to share with new emails, only with accounts already on the server, or on a trusted federated server.

**Comment by buffcode** [comment]
This is already provided by another extension:
- https://github.com/nextcloud/guests
- https://marketplace.owncloud.com/apps/guests

**Comment by nickvergessen** [comment]
As per above, this is exactly what the guests app is for.
