### ISSUE TITLE
We have some Userids which include spaces - is that meant to be possible? 

### ISSUE THREAD

**Issue by Daksol** [nextcloud/registration#383]
NC v22.x
We are using the Registration module.

It seems to allow a new user to self register a userid which contains an embedded space.

Is that meant to be allowed?

**Comment by nickvergessen** [comment]
Yeah the server code allows this
https://github.com/nextcloud/server/blob/master/lib/private/User/Manager.php#L426

If you don't like it you can use the user id regex option to limit it even more

**Comment by Daksol** [comment]
Thanks for this info.,

FYI the regular documentation does not mention space as a valid character in a username:-
https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_configuration.html#creating-a-new-user


![image](https://user-images.githubusercontent.com/42010857/153958680-9f73fbe2-04c9-4d04-9319-aac520e844e6.png)

**Comment by nickvergessen** [comment]
Doc fix in https://github.com/nextcloud/documentation/pull/8028
