### ISSUE TITLE
What table has the "Disabled users" listed?

### ISSUE THREAD

**Issue by HereIsJoe** [nextcloud/registration#386]
Those not yet registered show up in NextCloud in "User" section "Disabled users".
 The table "oc_users" have everybody with no distinction who is disabled or not.
 
In what DB table (oc_????)is it marked that someone is disabled?

**Comment by nickvergessen** [comment]
```sql
SELECT * FROM `oc_preferences` WHERE `appid` = 'core' AND `configkey` = 'enabled' AND `configvalue` = 'false';
```

**Comment by HereIsJoe** [comment]
Thank you!
