### ISSUE TITLE
Use new button component to fix focus issues

### ISSUE THREAD

**Issue by PVince81** [nextcloud/registration#391]
"Register" and "Request validation link" and "Verify", "Create account" buttons from must have focus highlight, try using the new button component from nextcloud-vue 5.0.0 to solve that.

Note: the button is only available in NC 24

**Comment by nickvergessen** [comment]
- [ ] Request validation link
- [ ] Verify
- [ ] Create account

The buttons currently have no special rules, so `input[type='submit']` from servers `guest.css` applies. Fixing there for everything should solve it:

```diff
diff --git a/core/css/guest.css b/core/css/guest.css
index ee2bf57c0c..2306177c3c 100644
--- a/core/css/guest.css
+++ b/core/css/guest.css
@@ -270,6 +270,10 @@ select {
        border-radius: 100px; /* --border-radius-pill */
        cursor: pointer;
 }
+input[type='submit']:focus {
+       color: #000;
+       border: 2px solid #000;
+}
 input[type='text'],
 input[type='tel'],
 input[type='password'],
```

- [ ] Register

I will try to fix manually first before moving to the new button component
