### ISSUE TITLE
Don't send welcome email

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/registration#408]
Hello,

When creating an account, the welcome email is not sent to the email address.
I wanted to test under nextcloud 24 but the application has not been updated :/

**Comment by JordanDIG** [comment]
Cc @nickvergessen

**Comment by nickvergessen** [comment]
Works fine here.

Can you share your settings?

**Comment by JordanDIG** [comment]
[https://s.jordand.fr/Clb90qZFlz.png](url)
[https://s.jordand.fr/EMFW4vEHRF.png](url)
[https://s.jordand.fr/BUsjYgZ08I.png](https://s.jordand.fr/BUsjYgZ08I.png)

**Comment by JordanDIG** [comment]
> Works fine here.
> 
> Can you share your settings?

[https://s.jordand.fr/Clb90qZFlz.png](https://s.jordand.fr/Clb90qZFlz.png)
[https://s.jordand.fr/EMFW4vEHRF.png](https://s.jordand.fr/EMFW4vEHRF.png)
[https://s.jordand.fr/BUsjYgZ08I.png](https://s.jordand.fr/BUsjYgZ08I.png)

**Comment by nickvergessen** [comment]
Works here with those settings.
Anything logged in your nextcloud.log?

**Comment by JordanDIG** [comment]
> Works here with those settings.
> Anything logged in your nextcloud.log?

No unfortunately :/

**Comment by JordanDIG** [comment]
> Works here with those settings. Anything logged in your nextcloud.log?

I have no particular error.
Just the mail is not sent, I have to resend it via the "Resend verification mail" button on the Nextcloud interface

**Comment by JordanDIG** [comment]
You can test if you want on my nextcloud instance...

**Comment by JordanDIG** [comment]
I don't understand why it works for you but not for me. Do you want to test from my instance? @nickvergessen

**Comment by nickvergessen** [comment]
No. The app works fine. Feel free to check if you configured your mail settings correctly and also make sure the normal user management setting to send the welcome email is enabled.

**Comment by JordanDIG** [comment]
> No. The app works fine. Feel free to check if you configured your mail settings correctly and also make sure the normal user management setting to send the welcome email is enabled.

How to enable normal user management setting to send the welcome email ?

**Comment by JordanDIG** [comment]
The emails are well configured in nextcloud, I received an email again this morning
