### ISSUE TITLE
Nextcloud 24: Black text

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/registration#410]
Hello,
I have an instance under nextcloud 24 and although the registration application is marked as incompatible, I forced the installation and on the connection page the text of the button to register is displayed in black

Cc @nickvergessen

**Comment by nickvergessen** [comment]
Yeah, the reason is it is not compatible 🤷‍♂️

See https://github.com/nextcloud/registration/pull/393 and linked issues
