### ISSUE TITLE
Request Verification Link, Verification ID input field is not showing up 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/registration#427]
### Steps to reproduce
1. Click on the registration link
2. Insert your email address and click on requesting verification link

### Expected behavior
Verify input field must be shown and an email should be sent to an email address 

### Actual behavior
It reloads and nothing changes, the email I inserted just stays in an email input field 

### Server configuration
**Operating system**: Fedora Server 35
Fedora Server 35
**Web server:**
Apache
**Database:**
PostgreSQL
**PHP version:**
PHP 8.0.18
**Nextcloud version:** (see Nextcloud admin page)
23.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older Nextcloud
**Where did you install Nextcloud from:**
Official website
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - analytics: 4.2.1
  - announcementcenter: 6.2.0
  - appointments: 1.12.3
  - apporder: 0.15.0
  - approval: 1.0.9
  - calendar: 3.2.2
  - camerarawpreviews: 0.7.15
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - duplicatefinder: 0.0.14
  - external: 3.10.2
  - extract: 1.3.5
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_automatedtagging: 1.13.0
  - files_downloadactivity: 1.13.0
  - files_external: 1.15.0
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_texteditor: 2.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - flow_notifications: 1.2.0
  - forms: 2.5.0
  - geoblocker: 0.5.4
  - groupfolders: 11.1.2
  - integration_github: 1.0.2
  - login_notes: 1.0.4
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - maps: 0.1.10
  - metadata: 0.16.0
  - music: 1.5.1
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quicknotes: 0.7.3
  - quota_warning: 1.14.0
  - rainloop: 7.2.5
  - recommendations: 1.2.0
  - registration: 1.5.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflow_ocr: 1.23.2
  - workflow_pdf_converter: 1.8.0
  - workflow_script: 1.8.0
  - workflowengine: 2.5.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Firefox 99.0.1 
**Operating system:**
Fedora 35
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Wed May 04 09:56:39.480509 2022] [proxy_fcgi:error] [pid 2778:tid 95943] (70007)The timeout specified has expired: [client 192.168.22.106:42278] AH01075: Error dispatching request to : (polling)


```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
none related to this issue, or there is no new output as I click registration button or after that...
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:40:65
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:40:65
No OC found main.js:160:111294
Proxying an event bus of version 2.1.1 with 1.3.0 main.js:285:35749
JQMIGRATE: Migrate is installed, version 3.3.2 main.js:959:933
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1358:3634
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1358:3634
Proxying an event bus of version 2.1.1 with 1.3.0 comments-app.js:415:98027
OCA.Comments.View initialized comments-app.js:614:362
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1358:3634
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 6 main.js:1358:3634
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 main.js:1358:3634
session heartbeat polling started main.js:800:971
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 main.js:1358:3634
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. main.js:1358:3634
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 136 main.js:1358:3634
```
</details>

**Comment by KiaraGrouwstra** [comment]
I'm facing this issue as well. For what it's worth, my nextcloud can normally send emails just fine.
In the browser console I can see a POST request to `/apps/registration/` receiving a HTTP 200.

**Comment by nickvergessen** [comment]
> just realized we're not on the newest version of this app, tho 2.0 seems to need nextcloud 25.

You are also not on the latest Nextcloud 24 veresion which is 24.0.7 at the moment. Could also be worth a try.

**Comment by elhananjair** [comment]
hello @nickvergessen I tested it just now and am not receiving a link to verify, it just shows allowed emails after reload 

https://user-images.githubusercontent.com/69236638/220097225-fa5d72e3-d504-4df9-8a8e-56e11e092237.mp4

**Comment by elhananjair** [comment]
ok it seems the problem is with specifying allowed domains, I removed those I specified on setting and now things are working, but this shows that there might be a problem when you add some exceptions to allowed domains.

**Comment by nickvergessen** [comment]
The email list is `;` separated, not `,`
That should already solve it.

**Comment by elhananjair** [comment]
ow yeah, that was the problem thanks.
