### ISSUE TITLE
Improve spam protection

### ISSUE THREAD

**Issue by wehowski** [nextcloud/registration#437]
Hello,
I was affected by a behavior of registration app possibly leading to be banned (E-Mail Server).

### Steps to reproduce
1. Request an verification email from /apps/registration
2. Repeat step 1 for n times with the same email address as often you can within the same time

### Expected behaviour
The user should be able to request a verification mail only for a given maximum number within a time period.
Instead of sending n mail within 1 second to the same email address, the page should remember the user to watch the inbox or refer to further steps if this fails (e.g. contact).

### Actual behaviour
The app is sending verification mails to the same email address over and over again.

-------
**Dirty(!)** fix:

````PHP
if('cli' !== \PHP_SAPI && '/apps/registration/' === substr($_SERVER['REQUEST_URI'], 0, strlen('/apps/registration/'))&& isset($_POST['email'])){
	
 $file = sys_get_temp_dir().DIRECTORY_SEPARATOR."nextcloud-rfloodprotection".DIRECTORY_SEPARATOR."mail"    .\DIRECTORY_SEPARATOR.sha1($_POST['email']).strlen($_POST['email'])."txt";
	
	if(!is_dir(dirname($file))){
	  mkdir(dirname($file), 0777, true);
	}
	
  if(!file_exists($file) || filemtime($file) < time() - (86400 * 2)){
    file_put_contents($file, time().'|'.strip_tags($_SERVER['REMOTE_ADDR']));
  }else{
     header("HTTP/1.1 429 Too Many Requests");
    die('Please check your postbox! <a href="https://example.com">Go to Example</a><br />
	If you did not find the confirmation mail in your inbox, please <a href="https://example.com/support.html">contact us</a>!'); 
  }

}
````

**Comment by nickvergessen** [comment]
Actually we have spam protection already in place.
Current throttling is 5 attempts per user in 5 minutes.

**Comment by nickvergessen** [comment]
Can you check again if that really does not happen for you?
If you don't have Redis enabled you can see the attempts in `oc_ratelimit_entries` in the database

**Comment by wehowski** [comment]
Hallo und Danke nickvergessen,
I have one single entry in this table, when now posting this comment it is
2022-07-25 14:42:10 delete_after field.
There is a hash field in the DB, but moment please, I have to inspect the code how the hash is created, if it takes email address, ip, ...
...

**Comment by wehowski** [comment]
Yes, the 5 attempts limit is working correctly at my site.
However this seemed not to be enough, as I had to request a deban at one provider due to registration mails from the app, I added the dirty one mail per two days fix.

**Comment by nickvergessen** [comment]
> However this seemed not to be enough, as I had to request a deban at one provider due to registration mails from the app, I added the dirty one mail per two days fix.

Did they tell you how many emails your server send?

**Comment by wehowski** [comment]
Hello nickvergessen, 
I do not have information about a number of emails, I did not ask, and have no own log about this (privacy e.g.).
regards,
Till
