### ISSUE TITLE
Block temporary or fake email domains

### ISSUE THREAD

**Issue by cybe3rSecuR1ty** [nextcloud/registration#445]
The allowed mailing list can not be configured with more than one domain, it does not recognize the others, this must be corrected since anyone with bad intentions can register on the platform with a temporary, fake email or on the blacklist, if the accepted domains are not specified.

**Comment by nickvergessen** [comment]
> The allowed mailing list can not be configured with more than one domain,

You can specify multiple entries separated by `;`
That should work fine.

**Comment by adanmazzoli** [comment]
For example this does not work: hotmail.com; gmail.com; yahoo.com

**Comment by nickvergessen** [comment]
try to remove the space (but I agree we should strip of whitespaces)

**Comment by adanmazzoli** [comment]
Fixed the issue 👍

**Comment by adanmazzoli** [comment]
Thank you for your time, good job.

**Comment by nickvergessen** [comment]
Let's keep it open so i remember to fix the trimming
