### ISSUE TITLE
Final registration form can't be submitted 

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/registration#469]
### Steps to reproduce
1. Try to register on sermo
2. Successfully receive and enter verification token
3. Enter full name and password
4. Try to submit the form

### Expected behaviour
Form should be submitted to the server and registration should be finished.

### Actual behaviour
The button changes to loading state but returns after 1s. No request is made, the form is not submitted to the server.
Workaround was to call `requestSubmit()` on the form via console.

### Server configuration
Tested on sermo.

**Comment by nickvergessen** [comment]
Only happens in chrome
