### ISSUE TITLE
Challenge in asset compilations steps  

### ISSUE THREAD

**Issue by brunoalfred** [nextcloud/registration#480]
### Steps to reproduce
1. I clone the repository then install all the dependencies as specified in package.json using `npm install` command
2. I found out webpack and webpack-cli were needed so i decided to install them ` "webpack": "^5.74.0" `,
    `"webpack-cli": "^4.10.0" `.
3. I also added vue-loader as i faced a challenge to work with webpack and vue without vue loader. This made me update my webpack.config.js to look like 
```js
const path = require('path')
const webpackConfig = require('@nextcloud/webpack-vue-config')
const { VueLoaderPlugin } = require('vue-loader')
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');

webpackConfig.entry = {
    settings: path.join(__dirname, 'src', 'settings'),
    form: path.join(__dirname, 'src', 'form'),
}

webpackConfig.plugins.push(
    new VueLoaderPlugin(),
    new NodePolyfillPlugin()
)



module.exports = webpackConfig
```

4. When i run npm run build/dev/watch the out is

![Screenshot 2022-10-25 at 11 09 15](https://user-images.githubusercontent.com/55545250/197719435-aeb97260-cf97-4974-843a-69da95618e81.png)

How do i compile the assets for this app. Is there any detailed place for this? Please share if there is anything undocumented.

### Expected behaviour
I expected the the compilation to do smooth and obtain output js in `js/` folder.

### Actual behaviour
The compilation failed and made me add webpack, webpack-cli and vue-loader but still doesnt seem to solve.

**Comment by nickvergessen** [comment]
So if you are still on this app and not your forked signup app, you can simply run `npm ci` to install all needed packages as they are locked in package.json and package-lock.json
Webpack itself is not directly listed, but it comes with the `@nextcloud/webpack-vue-config` package:
https://github.com/nextcloud/registration/blob/master/package.json#L39
As long as you have node 16 and npm 7 or 8 that should work fine out of the box.

**Comment by brunoalfred** [comment]
Seems to work, i was using pnpm instead of npm. Thanks. I guess ill close this
