### ISSUE TITLE
🛠️ State of maintenance

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/registration#524]
While there are many things that could be done to further improve this app, this app is currently not maintained. This means:

- We assess the main functionality as done
- We are not updating this app for future releases
- We are welcoming anyone who would like to take over this app.

We would be more than excited, if you would like to collaborate with us. We would love to welcome co-maintainers.

If there is a strong business case for any development of this app, we will consider your wishes for our roadmap. Please [contact your account manager](https://nextcloud.com/enterprise/) to talk about the possibilities.

**Comment by FlattusBlastus** [comment]
I believe this should be core NC functionality. I use this tool to add users correctly and then allow users to associate their accounts with Social Login. Without this you'd have to pre-create accounts which was always SO MUCH EXTRA WORK.

**Comment by nickvergessen** [comment]
Due to a misunderstanding Andy accidentally deleted the comment from @tcitworld 

So here it is again:
---

Hi,

We at [Framasoft](https://framasoft.org/) - a non-profit association financed by donations - make extensive use of this app for [the](https://framadrive.org/) [various](https://framagenda.org/) [services](https://www.frama.space/) we provide based on Nextcloud. We have therefore decided to help with the maintenance of this app, having experience with various contributions to the Nextcloud ecosystem.

Thomas, on behalf of Framasoft

**Comment by Govi59** [comment]
I guess we can change the README saying "this app is currently not maintained" :tada:

**Comment by tcitworld** [comment]
Fixed, thanks

**Comment by IntensivePorpoises** [comment]
> Due to a misunderstanding Andy accidentally deleted the comment from [@tcitworld](https://github.com/tcitworld)
> ## So here it is again:
> 
> Hi,
> 
> We at [Framasoft](https://framasoft.org/) - a non-profit association financed by donations - make extensive use of this app for [the](https://framadrive.org/) [various](https://framagenda.org/) [services](https://www.frama.space/) we provide based on Nextcloud. We have therefore decided to help with the maintenance of this app, having experience with various contributions to the Nextcloud ecosystem.
> 
> Thomas, on behalf of Framasoft

I'm just some guy looking to run a NextCloud instance, but thank you!
