### ISSUE TITLE
2.1 use 1.5  css  ui

### ISSUE THREAD

**Issue by wangyangaa** [nextcloud/registration#530]
Excuse me, where is it.Will the previous 1.5.0 UI be used in the nextcloud25 ? A lot of my pages are not normal ,
I don't know how to use Vue,  So ask if there is a solution.
thank you very much.

now pages:
![图片](https://user-images.githubusercontent.com/50029644/228104688-e4848bd5-4a5b-4ae8-9b79-95f89538cb30.png)

i want to 1.5 pages:
![图片](https://user-images.githubusercontent.com/50029644/228104710-10f79ebe-ef31-4a58-970c-6400b1574204.png)

**Comment by tcitworld** [comment]
We don't have control on the login page appearance.
