### ISSUE TITLE
Account creation on ldap

### ISSUE THREAD

**Issue by jybeeL** [nextcloud/registration#64]
hi,

in user management, all new user who are created with the registration app are **stored** in **the local database of nextcloud.**
I specify one group for these new user and i accept the user creation only if there mail domain specified is authorized.
- For example :
i accept only the email address domain "blate.fr" and the new user is added in the group "friend"

### First :
Is it possible to specify where new user will be stored from a new menu in the admin panel ?
- For example : 
I want to store all new user in my ldap server.
My ldap has many groups, i would specify the groups of my ldap where the new user will be member after the account creation.

### Second :
Is it possible to add new user in different group if the domain name of his mail address is different of the domain specified in the configuration ?
- For example :
If the domain is "blate.fr", i add the new user in the group "friend"  (and all group of my ldap with this configuration)
If the domain is "other.fr", i add temporarely the new user in the group "temp".
The account is in the ldap server but not active.
A mail is sent for the admin who must to accept (or not)
If the admin accept this new user, he must choose the ldap groups for the new user and the account become active
If the admin refuse this new user, the temporarely account is deleted from ldap

thx :)

**Comment by jdkruzr** [comment]
Just wanted to add that this being able to create users in LDAP would be a MASSIVE benefit.

**Comment by nickvergessen** [comment]
This should be possible with the https://github.com/nextcloud/ldap_write_support app.
