### ISSUE TITLE
Make mail confirmation optional

### ISSUE THREAD

**Issue by rugk** [nextcloud/registration#65]
Please allow admins to disable the mail confirmation. Not everybody has setup their mail server yet. :wink:

When https://github.com/pellaeon/registration/issues/11 is implemented the registration would still be protected from bots.

**Comment by Intergalacticstoryteller** [comment]
Is this a feature that may become real any time soon? 

I am attempting to build my server off the internet so requiring email as a way of registering has become... hindering. Is it possible to bypass that requirement and just jump to the registration part of the process?

Thanks for any help. :)

**Comment by dersweet** [comment]
Hi,
I need this feature too. Is it possible to implement it? 
Thanks
