### ISSUE TITLE
'back' button missing on registration page

### ISSUE THREAD

**Issue by keunes** [nextcloud/registration#67]
When you click 'register' on the login page, to be lead to the page where you can register/apply for an account. When a user clicked the button accidentally or wanted to cancel, a 'back' (arrow) button would be nice.

**Comment by pellaeon** [comment]
Nice suggestion! I think I will implement this.

2017年4月16日 20:01，"Koen Glotzbach" <notifications@github.com>寫道：

**Comment by pellaeon** [comment]
Wait, why doesn't the user simply clicks "Back" on browser?

**Comment by keunes** [comment]
because you're hanging with your mouse around the login button rather than with the back button of the browser. Normally login and register actions can be switched on-site (without having to click the back button); just check how other sites deal with both options in one context :)

**Comment by cdamken** [comment]
@keunes Probably you can add a text in css: You are trying a registration to the owncloud, if you are already register go back to the login page
