### ISSUE TITLE
app not fully compliant with theming

### ISSUE THREAD

**Issue by keunes** [nextcloud/registration#68]
I would expect the 'register' button to be the same color as Nextcloud's 'login' button, but that's currently not the case.

**Comment by happyreacer** [comment]
Is that not a easy change? It would be very nice ;-)

**Comment by MariusBluem** [comment]
Is this still the case with Nextcloud 13? @keunes @happyreacer

**Comment by Peterede** [comment]
Yes, this is still an issue with Nextcloud 13.
