### ISSUE TITLE
Transmit forms via AJAX

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/registration#98]
Forms should be transmitted via ajax, not plain-old page-reloading form posts.

**Comment by pellaeon** [comment]
Why? Any up sides to that? I'd rather keep it usable without javascript.

**Comment by leonklingele-work** [comment]
https://github.com/strukturag/registration/commit/08c25768612a4d5dfbf3312b4c6c716af52b6c40 if you're interested.

**Comment by nickvergessen** [comment]
So Nextcloud doesn't really work without JS anymore anyway. On the other hand there is also no real strong benefit in doing it at the moment.
